let data={
 projects:[{id:'P001',name:'Kentfield Ct',city:'Laconia',start:'05/09/2026',stage:'Insulation',status:'In Progress'},{id:'P002',name:'Jewett St',city:'Manchester',start:'05/09/2026',stage:'Insulation',status:'In Progress'}],
 stages:[{projectId:'P001',name:'Demolition',sequence:2,status:'Complete',applies:true,notes:''},{projectId:'P001',name:'Insulation',sequence:8,status:'In Progress',applies:true,notes:''},{projectId:'P002',name:'Demolition',sequence:2,status:'Complete',applies:true,notes:''},{projectId:'P002',name:'Insulation',sequence:8,status:'In Progress',applies:true,notes:''}],
 labor:[{id:'L001',projectId:'P001',stage:'Demolition',worker:'Carlos',date:'05/09/2026',hours:8,rate:25,total:200},{id:'L002',projectId:'P001',stage:'Demolition',worker:'Dênis',date:'05/09/2026',hours:8,rate:25,total:200},{id:'L003',projectId:'P001',stage:'Demolition',worker:'Welber',date:'05/09/2026',hours:8,rate:25,total:200}],
 purchases:[{id:'PU001',projectId:'P001',vendor:'Home Depot',date:'05/09/2026',amount:292.28,category:'Unclassified',stage:'Demolition',status:'Pending classification',receipt:''}],
 items:[{id:'PI001',purchaseId:'PU001',description:'Receipt total pending itemization',quantity:1,unitCost:292.28,total:292.28,category:'Unclassified',stage:'Demolition'}],
 commitments:[]
};
const sheetId='1ie-edjTy56CM8190ksLVNeuaHt6jXJkZiMHJH2a82Dw';
const num=v=>Number(String(v??0).replace(/[^0-9.-]/g,''))||0;
const usd=n=>num(n).toLocaleString('en-US',{style:'currency',currency:'USD'});
const clean=v=>String(v??'').trim();
const esc=v=>clean(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const isClosed=p=>/closed|complete|completed|conclu[ií]d|fechad|finalizad/i.test(clean(p.status));
const projectStatus=p=>isClosed(p)?'Fechado':'Em andamento';
const statusPt=s=>({'Not Started':'Não iniciada','In Progress':'Em andamento','Waiting':'A confirmar','Complete':'Concluída','Not Applicable':'Não se aplica'}[s]||s||'A confirmar');
const statusClass=s=>({'Not Started':'not-started','In Progress':'in-progress','Waiting':'waiting','Complete':'complete','Not Applicable':'not-applicable'}[s]||'waiting');
function loadSheet(name,query=''){return new Promise((resolve,reject)=>{const cb='rsf_'+name+'_'+Date.now()+Math.floor(Math.random()*1000);const script=document.createElement('script');window[cb]=r=>{delete window[cb];script.remove();if(r.status==='error')reject(new Error(name));else resolve(r.table)};script.onerror=()=>reject(new Error(name));script.src=`https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?sheet=${encodeURIComponent(name)}&tqx=responseHandler:${cb}${query?'&tq='+encodeURIComponent(query):''}`;document.head.appendChild(script)})}
function rows(table){const headers=table.cols.map(c=>c.label);return table.rows.map(r=>Object.fromEntries(headers.map((h,i)=>{const cell=r.c[i];return[h,typeof cell?.v==='number'||typeof cell?.v==='boolean'?cell.v:(cell?.f??cell?.v??'')]}))).filter(x=>Object.values(x).some(v=>v!==''&&v!==null))}
async function refreshData(){try{const [projectRows,stageRows,laborRows,purchaseRows,itemRows,budgetRows]=await Promise.all([loadSheet('Projects'),loadSheet('Stages'),loadSheet('Labor'),loadSheet('Purchases'),loadSheet('Purchase_Items'),loadSheet('Budget_Sales',"select * where D = 'Committed Cost'")]);data.projects=rows(projectRows).map(x=>({id:clean(x.project_id),name:clean(x.project_name),city:clean(x.city),start:clean(x.start_date),stage:clean(x.current_stage),status:clean(x.status)})).filter(x=>x.id&&x.name);data.stages=rows(stageRows).map(x=>({projectId:clean(x.project_id),name:clean(x.stage),sequence:num(x.sequence),status:clean(x.status),applies:x.included_in_scope===true||clean(x.included_in_scope).toLowerCase()==='true',notes:clean(x.notes)}));data.labor=rows(laborRows).map(x=>({id:clean(x.labor_id),projectId:clean(x.project_id),stage:clean(x.stage),worker:clean(x.worker),date:clean(x.date),hours:num(x.hours),rate:num(x.rate),total:num(x.total)}));data.purchases=rows(purchaseRows).map(x=>({id:clean(x.purchase_id),projectId:clean(x.project_id),vendor:clean(x.vendor),date:clean(x.date),amount:num(x.amount),category:clean(x.category),stage:clean(x.stage),status:clean(x.status),receipt:clean(x.receipt_url)}));data.items=rows(itemRows).map(x=>({id:clean(x.item_id),purchaseId:clean(x.purchase_id),description:clean(x.description),quantity:num(x.quantity),unitCost:num(x.unit_cost),total:num(x.total),category:clean(x.category),stage:clean(x.stage)}));data.commitments=rows(budgetRows).map(x=>({id:clean(x.record_id),projectId:clean(x.project_id),stage:clean(x.stage),type:clean(x.record_type),amount:num(x.amount),date:clean(x.date),notes:clean(x.notes)}));selectedProjectId=null;path=[];render();document.body.dataset.synced='true'}catch(e){document.body.dataset.synced='fallback';console.error('Falha ao atualizar dados',e)}}
const view=document.querySelector('#view'),crumbs=document.querySelector('#crumbs');
let selectedProjectId=null,path=[],projectFilter='open',stageFilter='active';
function project(){return data.projects.find(x=>x.id===selectedProjectId)}
function purchase(id){return data.purchases.find(x=>x.id===id)}
function projectLabor(id=selectedProjectId){return data.labor.filter(x=>x.projectId===id)}
function projectPurchases(id=selectedProjectId){return data.purchases.filter(x=>x.projectId===id)}
function projectItems(id=selectedProjectId){const ids=new Set(projectPurchases(id).map(x=>x.id));return data.items.filter(x=>ids.has(x.purchaseId))}
function projectCommitments(id=selectedProjectId){return data.commitments.filter(x=>x.projectId===id)}
function normalizeCategory(category){if(/equipment|tool/i.test(category))return'Equipment & Tools';if(/material|consumable/i.test(category))return'Materials & Consumables';return'Other Purchases'}
function stageCosts(stage,id=selectedProjectId){const labor=projectLabor(id).filter(x=>x.stage===stage).reduce((a,x)=>a+x.total,0);const items=projectItems(id).filter(x=>x.stage===stage);const materials=items.filter(x=>normalizeCategory(x.category)==='Materials & Consumables').reduce((a,x)=>a+x.total,0);const equipment=items.filter(x=>normalizeCategory(x.category)==='Equipment & Tools').reduce((a,x)=>a+x.total,0);const other=items.filter(x=>normalizeCategory(x.category)==='Other Purchases').reduce((a,x)=>a+x.total,0);const committed=projectCommitments(id).filter(x=>x.stage===stage).reduce((a,x)=>a+x.amount,0);return{labor,materials,equipment,other,paid:labor+materials+equipment+other,committed}}
function projectTotals(id){const paid=projectLabor(id).reduce((a,x)=>a+x.total,0)+projectItems(id).reduce((a,x)=>a+x.total,0);const committed=projectCommitments(id).reduce((a,x)=>a+x.amount,0);const hours=projectLabor(id).reduce((a,x)=>a+x.hours,0);return{paid,committed,hours}}
function go(...parts){path=parts;render()}
function crumb(label,...parts){return `<button class="crumb" onclick='go(${parts.map(x=>JSON.stringify(x)).join(',')})'>${esc(label)}</button>`}
function openProject(id){selectedProjectId=id;path=[];stageFilter='active';render()}
function showProjects(){selectedProjectId=null;path=[];render()}
function setProjectFilter(filter){projectFilter=filter;render()}
function setStageFilter(filter){stageFilter=filter;render()}
function renderProjects(){const title=document.querySelector('#pageTitle'),subtitle=document.querySelector('#pageSubtitle'),status=document.querySelector('#pageStatus');title.textContent='Gestão à Vista';subtitle.textContent='Visão geral das obras';status.style.display='none';crumbs.innerHTML='';const open=data.projects.filter(p=>!isClosed(p)).length,closed=data.projects.length-open;const visible=data.projects.filter(p=>projectFilter==='all'||(projectFilter==='closed'?isClosed(p):!isClosed(p)));view.innerHTML=`<div class="projects-head"><h2 class="section-title">Projetos</h2><div class="filters"><button class="filter ${projectFilter==='all'?'active':''}" onclick="setProjectFilter('all')">Todos (${data.projects.length})</button><button class="filter ${projectFilter==='open'?'active':''}" onclick="setProjectFilter('open')">Abertos (${open})</button><button class="filter ${projectFilter==='closed'?'active':''}" onclick="setProjectFilter('closed')">Fechados (${closed})</button></div></div><div class="project-list">${visible.map(p=>{const t=projectTotals(p.id);return `<article class="card click project-card" onclick="openProject('${esc(p.id)}')"><div class="project-content"><div class="project-top"><div class="project-name">${esc(p.name)}</div><span class="project-status ${isClosed(p)?'closed':''}">${projectStatus(p)}</span></div><div class="note">${esc(p.city)} · Etapa atual: ${esc(p.stage||'Não informada')}</div><div class="project-money"><span><b>${usd(t.paid)}</b> pagos</span><span><b>${usd(t.committed)}</b> contratados</span></div></div><span class="project-arrow">›</span></article>`}).join('')||'<div class="empty-state">Nenhum projeto nesta categoria.</div>'}</div>`}
function renderStageOverview(){const p=project(),all=data.stages.filter(x=>x.projectId===p.id).sort((a,b)=>a.sequence-b.sequence);const visible=all.filter(s=>stageFilter==='all'||s.status!=='Not Applicable');const totals=projectTotals(p.id);const complete=all.filter(s=>s.status==='Complete').length;view.innerHTML=`<div class="project-summary"><div><span>Custos pagos</span><strong>${usd(totals.paid)}</strong></div><div><span>Custos contratados</span><strong>${usd(totals.committed)}</strong></div><div><span>Horas registradas</span><strong>${totals.hours} h</strong></div><div><span>Etapas concluídas</span><strong>${complete}/${all.length}</strong></div></div><div class="stage-toolbar"><h2 class="section-title">Custos por etapa</h2><div class="filters"><button class="filter ${stageFilter==='active'?'active':''}" onclick="setStageFilter('active')">Aplicáveis</button><button class="filter ${stageFilter==='all'?'active':''}" onclick="setStageFilter('all')">Todas</button></div></div><div class="stage-list">${visible.map(s=>{const c=stageCosts(s.name);return `<article class="stage-card click" onclick="go('Etapa','${esc(s.name)}')"><div class="stage-order">${s.sequence}</div><div class="stage-main"><div class="stage-title"><strong>${esc(s.name)}</strong><span class="stage-status ${statusClass(s.status)}">${statusPt(s.status)}</span></div>${s.notes?`<div class="note">${esc(s.notes)}</div>`:''}<div class="stage-money"><span>Pago <b>${usd(c.paid)}</b></span><span>Contratado <b>${usd(c.committed)}</b></span></div></div><span class="project-arrow">›</span></article>`}).join('')}</div>`}
function categoryRows(stage){const c=stageCosts(stage);return[['Labor',c.labor],['Materials & Consumables',c.materials],['Equipment & Tools',c.equipment],['Other Purchases',c.other],['Committed Costs',c.committed]].filter(x=>x[1]>0)}
function renderStage(stage){const s=data.stages.find(x=>x.projectId===selectedProjectId&&x.name===stage),c=stageCosts(stage),categories=categoryRows(stage);view.innerHTML=`<div class="stage-heading"><div><h2 class="section-title">${esc(stage)}</h2><span class="stage-status ${statusClass(s?.status)}">${statusPt(s?.status)}</span></div><div class="stage-total"><span>Pago <b>${usd(c.paid)}</b></span><span>Contratado <b>${usd(c.committed)}</b></span></div></div>${s?.notes?`<div class="stage-note">${esc(s.notes)}</div>`:''}<div class="list">${categories.map(([name,value])=>`<div class="row click" onclick="go('Etapa','${esc(stage)}','${esc(name)}')"><span><strong>${esc(name)}</strong><div class="note">Clique para ver os detalhes</div></span><span class="money">${usd(value)}</span></div>`).join('')||'<div class="empty-state">Ainda não existem custos registrados nesta etapa.</div>'}</div>`}
function renderCategory(stage,category){let entries=[];if(category==='Labor')entries=projectLabor().filter(x=>x.stage===stage).map(x=>({id:x.id,title:x.worker,note:`${x.hours}h × ${usd(x.rate)}/h`,amount:x.total,type:'labor'}));else if(category==='Committed Costs')entries=projectCommitments().filter(x=>x.stage===stage).map(x=>({id:x.id,title:/electrical/i.test(x.stage)?'Eletricista':'Henry Plumber Services',note:'Pagamento não confirmado',amount:x.amount,type:'commitment'}));else entries=projectItems().filter(x=>x.stage===stage&&normalizeCategory(x.category)===category).map(x=>({id:x.id,title:x.description,note:`${x.quantity} × ${usd(x.unitCost)}`,amount:x.total,type:'item'}));view.innerHTML=`<h2 class="section-title">${esc(category)} · ${esc(stage)}</h2><div class="list">${entries.map(x=>`<div class="row click" onclick="go('Etapa','${esc(stage)}','${esc(category)}','${esc(x.type)}','${esc(x.id)}')"><span><strong>${esc(x.title)}</strong><div class="note">${esc(x.note)}</div></span><span class="money">${usd(x.amount)}</span></div>`).join('')||'<div class="empty-state">Nenhum lançamento nesta categoria.</div>'}</div>`}
function renderDetail(stage,category,type,id){if(type==='labor'){const x=data.labor.find(y=>y.id===id);view.innerHTML=`<h2 class="section-title">Lançamento de mão de obra</h2><article class="card detail"><strong>${esc(x.worker)}</strong><br>Etapa: ${esc(x.stage)}<br>Data: ${esc(x.date)}<br>Horas: ${x.hours}<br>Taxa: ${usd(x.rate)}/h<br><strong>Total: ${usd(x.total)}</strong></article>`;return}if(type==='commitment'){const x=data.commitments.find(y=>y.id===id);view.innerHTML=`<h2 class="section-title">Custo contratado</h2><article class="card detail"><strong>${/electrical/i.test(x.stage)?'Eletricista':'Henry Plumber Services'}</strong><br>Etapa: ${esc(x.stage)}<br>Valor contratado: <strong>${usd(x.amount)}</strong><br>Status do pagamento: <strong>Não confirmado</strong>${x.date?`<br>Data do orçamento: ${esc(x.date)}`:''}<br><span class="note">${esc(x.notes)}</span></article>`;return}const x=data.items.find(y=>y.id===id),p=purchase(x.purchaseId);view.innerHTML=`<h2 class="section-title">Detalhe da compra</h2><article class="card detail"><strong>${esc(x.description)}</strong><br>Loja: ${esc(p?.vendor)}<br>Data: ${esc(p?.date)}<br>Quantidade: ${x.quantity}<br>Preço unitário: ${usd(x.unitCost)}<br>Categoria: ${esc(x.category)}<br><strong>Total: ${usd(x.total)}</strong><br>Comprovante: ${p?.receipt?`<a href="${esc(p.receipt)}" target="_blank" rel="noopener">abrir comprovante</a>`:'<span class="empty">link ainda não informado</span>'}</article>`}
function render(){if(!selectedProjectId){renderProjects();return}const p=project();if(!p){showProjects();return}const title=document.querySelector('#pageTitle'),subtitle=document.querySelector('#pageSubtitle'),status=document.querySelector('#pageStatus');title.textContent=p.name;subtitle.textContent=`${p.city} · Início ${p.start}`;status.style.display='inline-block';status.textContent=projectStatus(p);crumbs.innerHTML=`<button class="back-home" onclick="showProjects()">← Voltar para todos os projetos</button><div class="trail">${crumb('Custos por etapa')}${path.length?' › '+path.slice(1).map((x,i)=>crumb(x,...path.slice(0,i+2))).join(' › '):''}</div>`;if(!path.length){renderStageOverview();return}const [,stage,category,type,id]=path;if(!category){renderStage(stage);return}if(!type){renderCategory(stage,category);return}renderDetail(stage,category,type,id)}
render();refreshData();
