let data={projects:[{id:'P001',name:'Kentfield Ct',city:'Laconia',start:'05/09/2026',stage:'Insulation',status:'In Progress'}],labor:[{id:'L001',projectId:'P001',worker:'Carlos',stage:'Demolition',date:'05/09/2026',hours:8,rate:25,total:200},{id:'L002',projectId:'P001',worker:'Dênis',stage:'Demolition',date:'05/09/2026',hours:8,rate:25,total:200},{id:'L003',projectId:'P001',worker:'Welber',stage:'Demolition',date:'05/09/2026',hours:8,rate:25,total:200}],purchases:[{id:'PU001',projectId:'P001',vendor:'Home Depot',date:'05/09/2026',stage:'Demolition',amount:292.28,category:'Unclassified',receipt:''}]};
const sheetId='1ie-edjTy56CM8190ksLVNeuaHt6jXJkZiMHJH2a82Dw';
const num=v=>Number(String(v??0).replace(/[^0-9.-]/g,''))||0;
const usd=n=>num(n).toLocaleString('en-US',{style:'currency',currency:'USD'});
const clean=v=>String(v??'').trim();
const isClosed=p=>/closed|complete|completed|conclu[ií]d|fechad|finalizad/i.test(clean(p.status));
const statusLabel=p=>isClosed(p)?'Fechado':'Em andamento';
function loadSheet(name){return new Promise((resolve,reject)=>{const cb='rsf_'+name+'_'+Date.now();const script=document.createElement('script');window[cb]=r=>{delete window[cb];script.remove();if(r.status==='error')reject(new Error(name));else resolve(r.table)};script.onerror=()=>reject(new Error(name));script.src=`https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?sheet=${encodeURIComponent(name)}&tqx=responseHandler:${cb}`;document.head.appendChild(script)})}
function rows(table){const headers=table.cols.map(c=>c.label);return table.rows.map(r=>Object.fromEntries(headers.map((h,i)=>{const cell=r.c[i];return [h,typeof cell?.v==='number'?cell.v:(cell?.f??cell?.v??'')]}))).filter(x=>Object.values(x).some(Boolean))}
async function refreshData(){try{const [projectRows,laborRows,purchaseRows]=await Promise.all(['Projects','Labor','Purchases'].map(loadSheet));data.projects=rows(projectRows).map(x=>({id:clean(x.project_id),name:clean(x.project_name),city:clean(x.city),start:clean(x.start_date),stage:clean(x.current_stage),status:clean(x.status)})).filter(x=>x.id&&x.name);data.labor=rows(laborRows).map(x=>({id:clean(x.labor_id),projectId:clean(x.project_id),worker:clean(x.worker),stage:clean(x.stage),date:clean(x.date),hours:num(x.hours),rate:num(x.rate),total:num(x.total)}));data.purchases=rows(purchaseRows).map(x=>({id:clean(x.purchase_id),projectId:clean(x.project_id),vendor:clean(x.vendor),date:clean(x.date),stage:clean(x.stage),amount:num(x.amount),category:clean(x.category),receipt:clean(x.receipt_url)}));selectedProjectId=null;path=[];render();document.body.dataset.synced='true'}catch(e){document.body.dataset.synced='fallback'}}
const view=document.querySelector('#view'),crumbs=document.querySelector('#crumbs');
let selectedProjectId=null,path=[],projectFilter='open';
function project(){return data.projects.find(x=>x.id===selectedProjectId)}
function projectLabor(){return data.labor.filter(x=>x.projectId===selectedProjectId)}
function projectPurchases(){return data.purchases.filter(x=>x.projectId===selectedProjectId)}
function totals(id){const rows=data.labor.filter(x=>x.projectId===id),buys=data.purchases.filter(x=>x.projectId===id);const labor=rows.reduce((a,x)=>a+num(x.total),0),purchases=buys.reduce((a,x)=>a+num(x.amount),0),hours=rows.reduce((a,x)=>a+num(x.hours),0);return{labor,purchases,hours,total:labor+purchases}}
function go(...parts){path=parts;render()}
function crumb(label,...parts){return `<button class="crumb" onclick='go(${parts.map(x=>JSON.stringify(x)).join(',')})'>${label}</button>`}
function openProject(id){selectedProjectId=id;path=[];render()}
function showProjects(){selectedProjectId=null;path=[];render()}
function setFilter(filter){projectFilter=filter;render()}
function renderProjects(){const title=document.querySelector('#pageTitle'),subtitle=document.querySelector('#pageSubtitle'),status=document.querySelector('#pageStatus');title.textContent='Gestão à Vista';subtitle.textContent='Visão geral das obras';status.style.display='none';crumbs.innerHTML='';const openCount=data.projects.filter(p=>!isClosed(p)).length,closedCount=data.projects.length-openCount;const visible=data.projects.filter(p=>projectFilter==='all'||(projectFilter==='closed'?isClosed(p):!isClosed(p)));view.innerHTML=`<div class="projects-head"><h2 class="section-title">Projetos</h2><div class="filters" aria-label="Filtrar projetos"><button class="filter ${projectFilter==='all'?'active':''}" onclick="setFilter('all')">Todos (${data.projects.length})</button><button class="filter ${projectFilter==='open'?'active':''}" onclick="setFilter('open')">Abertos (${openCount})</button><button class="filter ${projectFilter==='closed'?'active':''}" onclick="setFilter('closed')">Fechados (${closedCount})</button></div></div><div class="project-list">${visible.map(p=>{const t=totals(p.id);return `<article class="card click project-card" onclick="openProject('${p.id}')"><div><div class="project-top"><div class="project-name">${p.name}</div><span class="project-status ${isClosed(p)?'closed':''}">${statusLabel(p)}</span></div><div class="note">${p.city} · Etapa atual: ${p.stage||'Não informada'}</div><div class="note">${usd(t.total)} gastos · ${t.hours} horas</div></div><span class="project-arrow">›</span></article>`}).join('')||'<div class="empty-state">Nenhum projeto nesta categoria.</div>'}</div>`}
function render(){if(!selectedProjectId){renderProjects();return}const p=project();if(!p){showProjects();return}const t=totals(p.id),laborRows=projectLabor(),purchaseRows=projectPurchases();const title=document.querySelector('#pageTitle'),subtitle=document.querySelector('#pageSubtitle'),status=document.querySelector('#pageStatus');title.textContent=p.name;subtitle.textContent=`${p.city} · Início ${p.start}`;status.style.display='inline-block';status.textContent=statusLabel(p);crumbs.innerHTML=`<button class="back-home" onclick="showProjects()">← Voltar para todos os projetos</button><div class="trail">${crumb('Visão geral')}${path.length?' › '+path.map((x,i)=>crumb(x,...path.slice(0,i+1))).join(' › '):''}</div>`;const [a,b,stage]=path;
 if(!a){view.innerHTML=`<div class="grid"><article class="card"><div class="label">Etapa atual</div><div class="value">${p.stage||'Não informada'}</div></article><article class="card click" onclick="go('Gastos')"><div class="label">Gasto até agora</div><div class="value">${usd(t.total)}</div><div class="note">Clique para detalhar</div></article><article class="card"><div class="label">Horas trabalhadas</div><div class="value">${t.hours} h</div></article></div>${purchaseRows.some(x=>/unclassified|pending|classificar/i.test(x.category))?`<h2 class="section-title attention-title">Atenção</h2>${purchaseRows.filter(x=>/unclassified|pending|classificar/i.test(x.category)).map(x=>`<div class="row warning"><span>Compra ${x.vendor} pendente de classificação</span><strong>${usd(x.amount)}</strong></div>`).join('')}`:''}`;return}
 if(a==='Gastos'&&!b){view.innerHTML=`<h2 class="section-title">Gastos</h2><div class="list"><div class="row click" onclick="go('Gastos','Labor')"><span><strong>Labor</strong><div class="note">${t.hours} horas · ${new Set(laborRows.map(x=>x.worker)).size} trabalhadores</div></span><span class="money">${usd(t.labor)}</span></div>${purchaseRows.map(x=>`<div class="row click ${/unclassified/i.test(x.category)?'warning':''}" onclick="go('Gastos','Compras','${x.id}')"><span><strong>${x.category||'A classificar'}</strong><div class="note">${x.vendor} · ${x.stage}</div></span><span class="money">${usd(x.amount)}</span></div>`).join('')}<div class="row"><strong>Total</strong><span class="money">${usd(t.total)}</span></div></div>`;return}
 if(a==='Gastos'&&b==='Labor'&&!stage){const stages=[...new Set(laborRows.map(x=>x.stage).filter(Boolean))];view.innerHTML=`<h2 class="section-title">Labor por etapa</h2><div class="list">${stages.map(s=>{const entries=laborRows.filter(x=>x.stage===s);return `<div class="row click" onclick="go('Gastos','Labor','${s}')"><span><strong>${s}</strong><div class="note">${entries.reduce((a,x)=>a+x.hours,0)} horas</div></span><span class="money">${usd(entries.reduce((a,x)=>a+x.total,0))}</span></div>`}).join('')||'<div class="empty-state">Nenhum lançamento de labor.</div>'}</div>`;return}
 if(a==='Gastos'&&b==='Labor'&&stage&&!path[3]){const entries=laborRows.filter(x=>x.stage===stage);view.innerHTML=`<h2 class="section-title">${stage} · trabalhadores</h2><div class="list">${entries.map(x=>`<div class="row click" onclick="go('Gastos','Labor','${stage}','${x.id}')"><span><strong>${x.worker}</strong><div class="note">${x.hours}h × ${usd(x.rate)}/h</div></span><span class="money">${usd(x.total)}</span></div>`).join('')}</div>`;return}
 if(a==='Gastos'&&b==='Labor'&&path[3]){const x=laborRows.find(y=>y.id===path[3]);if(x)view.innerHTML=`<h2 class="section-title">Lançamento de labor</h2><article class="card detail"><strong>${x.worker}</strong><br>Etapa: ${x.stage}<br>Data: ${x.date}<br>Horas: ${x.hours}<br>Taxa: ${usd(x.rate)}/h<br><strong>Total: ${usd(x.total)}</strong></article>`;return}
 if(a==='Gastos'&&b==='Compras'){const x=purchaseRows.find(y=>y.id===stage);if(x)view.innerHTML=`<h2 class="section-title">Compra</h2><article class="card detail ${/unclassified/i.test(x.category)?'warning':''}"><strong>${x.vendor}</strong><br>Data: ${x.date}<br>Etapa: ${x.stage}<br>Categoria: ${x.category||'A classificar'}<br><strong>Total: ${usd(x.amount)}</strong><br>Comprovante: ${x.receipt?`<a href="${x.receipt}" target="_blank" rel="noopener">abrir comprovante</a>`:'<span class="empty">link ainda não informado</span>'}</article>`;return}
}
render();refreshData();
