let data={project:{name:'Kentfield Ct',city:'Laconia',start:'05/09/2026',stage:'Insulation',status:'Em andamento'},labor:[{worker:'Carlos',stage:'Demolition',date:'05/09/2026',hours:8,rate:25,total:200},{worker:'Dênis',stage:'Demolition',date:'05/09/2026',hours:8,rate:25,total:200},{worker:'Welber',stage:'Demolition',date:'05/09/2026',hours:8,rate:25,total:200}],purchases:[{id:'PU001',vendor:'Home Depot',date:'05/09/2026',stage:'Demolition',amount:292.28,category:'Unclassified',receipt:''}],sales:[{stage:'Drywall',amount:19000}],scope:'Limpeza final não faz parte do escopo'};
const usd=n=>Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD'}); let labor=0,purchases=0,total=0,hours=0,sold=0;
function recalc(){labor=data.labor.reduce((a,x)=>a+Number(x.total||0),0);purchases=data.purchases.reduce((a,x)=>a+Number(x.amount||0),0);total=labor+purchases;hours=data.labor.reduce((a,x)=>a+Number(x.hours||0),0);sold=data.sales.reduce((a,x)=>a+Number(x.amount||0),0)}
recalc();
const sheetId='1ie-edjTy56CM8190ksLVNeuaHt6jXJkZiMHJH2a82Dw';
function loadSheet(name){return new Promise((resolve,reject)=>{const cb='rsf_'+name+'_'+Date.now();const script=document.createElement('script');window[cb]=r=>{delete window[cb];script.remove();if(r.status==='error')reject(new Error(name));else resolve(r.table)};script.onerror=()=>reject(new Error(name));script.src=`https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?sheet=${encodeURIComponent(name)}&tqx=responseHandler:${cb}`;document.head.appendChild(script)})}
function rows(table){const headers=table.cols.map(c=>c.label);return table.rows.map(r=>Object.fromEntries(headers.map((h,i)=>{const cell=r.c[i];return [h,typeof cell?.v==='number'?cell.v:(cell?.f??cell?.v??'')]}))).filter(x=>Object.values(x).some(Boolean))}
async function refreshData(){try{const [projects,laborRows,purchaseRows,saleRows]=await Promise.all(['Projects','Labor','Purchases','Budget_Sales'].map(loadSheet));const p=rows(projects)[0];data.project={name:p.project_name,city:p.city,start:p.start_date,stage:p.current_stage,status:p.status};data.labor=rows(laborRows).map(x=>({worker:x.worker,stage:x.stage,date:x.date,hours:Number(x.hours),rate:Number(x.rate),total:Number(x.total)}));data.purchases=rows(purchaseRows).map(x=>({id:x.purchase_id,vendor:x.vendor,date:x.date,stage:x.stage,amount:Number(x.amount),category:x.category,receipt:x.receipt_url}));data.sales=rows(saleRows).filter(x=>x.record_type==='Sale').map(x=>({stage:x.stage,amount:Number(x.amount)}));recalc();path=[];render();document.body.dataset.synced='true'}catch(e){document.body.dataset.synced='fallback'}}
const view=document.querySelector('#view'), crumbs=document.querySelector('#crumbs'); let path=[];
function go(...p){path=p;render()}; function c(label,...p){return `<button class="crumb" onclick='go(${p.map(x=>JSON.stringify(x)).join(',')})'>${label}</button>`}
function render(){crumbs.innerHTML=c('Visão geral')+(path.length?' › '+path.map((x,i)=>c(x,...path.slice(0,i+1))).join(' › '):''); const [a,b,c1]=path;
 if(!a){view.innerHTML=`<div class="grid"><article class="card"><div class="label">Etapa atual</div><div class="value">${data.project.stage}</div></article><article class="card click" onclick="go('Gastos')"><div class="label">Gasto até agora</div><div class="value">${usd(total)}</div><div class="note">Clique para detalhar</div></article><article class="card"><div class="label">Horas trabalhadas</div><div class="value">${hours} h</div></article><article class="card click" onclick="go('Vendas')"><div class="label">Valor vendido conhecido</div><div class="value">${usd(sold)}</div><div class="note">Drywall</div></article></div><h2 class="section-title" style="margin-top:24px">Atenção</h2><div class="row warning"><span>Compra Home Depot pendente de classificação</span><strong>${usd(purchases)}</strong></div>`;return}
 if(a==='Gastos'&&!b){view.innerHTML=`<h2 class="section-title">Gastos</h2><div class="list"><div class="row click" onclick="go('Gastos','Labor')"><span><strong>Labor</strong><div class="note">24 horas · 3 trabalhadores</div></span><span class="money">${usd(labor)}</span></div><div class="row click warning" onclick="go('Gastos','A classificar')"><span><strong>A classificar</strong><div class="note">Home Depot · material/consumível ou equipamento/ferramenta</div></span><span class="money">${usd(purchases)}</span></div><div class="row"><strong>Total</strong><span class="money">${usd(total)}</span></div></div>`;return}
 if(a==='Gastos'&&b==='Labor'&&!c1){view.innerHTML=`<h2 class="section-title">Labor por etapa</h2><div class="row click" onclick="go('Gastos','Labor','Demolition')"><span><strong>Demolition</strong><div class="note">24 horas</div></span><span class="money">${usd(labor)}</span></div>`;return}
 if(a==='Gastos'&&b==='Labor'&&c1==='Demolition'&&!path[3]){view.innerHTML=`<h2 class="section-title">Demolition · trabalhadores</h2><div class="list">${data.labor.map(x=>`<div class="row click" onclick="go('Gastos','Labor','Demolition','${x.worker}')"><span><strong>${x.worker}</strong><div class="note">${x.hours}h × ${usd(x.rate)}/h</div></span><span class="money">${usd(x.total)}</span></div>`).join('')}</div>`;return}
 if(a==='Gastos'&&b==='Labor'&&c1==='Demolition'&&path[3]){const x=data.labor.find(y=>y.worker===path[3]);view.innerHTML=`<h2 class="section-title">Lançamento de labor</h2><article class="card detail"><strong>${x.worker}</strong><br>Etapa: ${x.stage}<br>Data: ${x.date}<br>Horas: ${x.hours}<br>Taxa: ${usd(x.rate)}/h<br><strong>Total: ${usd(x.total)}</strong></article>`;return}
 if(a==='Gastos'&&b==='A classificar'){const x=data.purchases[0];view.innerHTML=`<h2 class="section-title">Compra</h2><article class="card detail warning"><strong>${x.vendor}</strong><br>Data: ${x.date}<br>Etapa: ${x.stage}<br>Categoria: ${x.category}<br><strong>Total: ${usd(x.amount)}</strong><br>Comprovante: <span class="empty">link ainda não informado</span></article>`;return}
 if(a==='Vendas'){view.innerHTML=`<h2 class="section-title">Vendas conhecidas</h2><div class="list">${data.sales.map(x=>`<div class="row"><strong>${x.stage}</strong><span class="money">${usd(x.amount)}</span></div>`).join('')}</div>`;return}}
render();refreshData();
