let reportImport=null,reportImportError='',reportRemember=true;
let reportNormalizedCache={labor:null,projects:null,rows:null};
function reportNormalized(source){if(reportNormalizedCache.labor!==source.labor||reportNormalizedCache.projects!==source.projects)reportNormalizedCache={labor:source.labor,projects:source.projects,rows:RSFTime.normalize(source.labor,source.projects)};return reportNormalizedCache.rows}
function reportKeep(value){reportRemember=value;if(value)reportSaveImport();else try{localStorage.removeItem(reportStorageKey)}catch(e){}renderTimeReport()}
const reportStorageKey='rsf-time-report-import-v1';
try{const saved=JSON.parse(localStorage.getItem(reportStorageKey)||'null');if(saved&&Array.isArray(saved.labor)&&Array.isArray(saved.projects))reportImport=saved}catch(e){/* Storage may be disabled by the browser. */}
function reportSaveImport(){if(!reportRemember)return true;try{localStorage.setItem(reportStorageKey,JSON.stringify(reportImport));reportImportError='';return true}catch(e){reportImportError='Não foi possível guardar neste navegador. Os registros continuam disponíveis até recarregar.';return false}}

async function reportImportFile(file){
 if(!file)return;
 try{if(file.size>2000000)throw new Error('Arquivo muito grande. Limite: 2 MB.');const parsed=JSON.parse(await file.text());if(!parsed||typeof parsed!=='object'||!Array.isArray(parsed.labor)||!Array.isArray(parsed.projects)||parsed.labor.length>10000||parsed.labor.some(r=>!r||typeof r!=='object')||parsed.projects.some(r=>!r||typeof r!=='object'))throw new Error('Formato inválido: são necessárias listas labor e projects.');reportImport={labor:parsed.labor,projects:parsed.projects,label:String(parsed.label||file.name),capturedAt:typeof parsed.capturedAt==='string'&&Number.isFinite(Date.parse(parsed.capturedAt))?parsed.capturedAt:null,importedAt:new Date().toISOString()};reportImportError='';reportSaveImport();const dates=parsed.labor.map(r=>RSFTime.dateKey(r.date)).filter(Boolean).sort();reportReset();if(dates.length){reportFilters.day=dates.at(-1);reportFilters.from=dates[0];reportFilters.to=dates.at(-1)}renderTimeReport()}catch(e){reportImportError=e.message;renderTimeReport()}
}
function reportClearImport(){try{localStorage.removeItem(reportStorageKey)}catch(e){}reportImport=null;reportImportError='';reportReset()}
function reportSourceControls(){return `<div class="report-source"><strong>${reportImport?'Arquivo carregado: '+esc(reportImport.label):'Fonte: planilha conectada'}</strong><p class="note">Carregue um arquivo JSON de segmentos para conferir outros registros. Os registros carregados ficam guardados somente neste navegador. Não são enviados à planilha nem misturados com ela. Para atualizar a consulta, carregue um arquivo mais recente.</p>${reportImport?`<p class="note">Consulta da origem: ${reportImport.capturedAt?esc(new Date(reportImport.capturedAt).toLocaleString('pt-BR')):'horário não informado'} · Carregada em: ${reportImport.importedAt?esc(new Date(reportImport.importedAt).toLocaleString('pt-BR')):'horário não informado'}. Esta consulta não atualiza automaticamente.</p><label class="report-check"><input type="checkbox" ${reportRemember?'checked':''} onchange="reportKeep(this.checked)"> Guardar consulta neste navegador</label>`:''}<label class="report-file">Carregar registros (JSON)<input type="file" accept=".json,application/json" onchange="reportImportFile(this.files[0])"></label>${reportImport?'<button class="filter" onclick="reportClearImport()">Remover consulta e voltar à planilha</button>':''}${reportImportError?'<p role="alert">'+esc(reportImportError)+'</p>':''}</div>`}
const reportToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const reportFilters={mode:'today',day:reportToday(),from:reportToday().slice(0,8)+'01',to:reportToday(),worker:'',project:'',client:'',status:'',sort:'desc',consolidate:false};
function reportSet(key,value){reportFilters[key]=key==='day'&&!value?reportToday():value;renderTimeReport()}
function reportReset(){Object.assign(reportFilters,{day:reportToday(),from:reportToday().slice(0,8)+'01',to:reportToday(),worker:'',project:'',client:'',status:'',sort:'desc'});renderTimeReport()}
function reportOptions(values,current){return '<option value="">Todos</option>'+values.map(([value,label])=>`<option value="${esc(value)}" ${value===current?'selected':''}>${esc(label)}</option>`).join('')}
function reportGroupHours(g){const pending=g.segments.filter(r=>r.minutes===null).length;return (pending===g.segments.length?'A confirmar':RSFTime.duration(g.minutes))+(pending&&pending<g.segments.length?' (parcial)':'')}
function reportDate(value){return value?value.split('-').reverse().join('/'):'Data inválida'}
function reportTable(headers,body){return `<div class="report-table-wrap" tabindex="0" aria-label="Tabela de ponto, role horizontalmente se necessário"><table class="report-table"><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div>`}
function renderTimeReport(){
 const f=reportFilters,core=RSFTime;
 document.querySelector('#pageTitle').textContent='Relatório de Ponto';
 document.querySelector('#pageSubtitle').textContent='Horas por funcionário e por cliente / projeto';
 document.querySelector('#pageStatus').style.display='none';crumbs.innerHTML='';
 const footer=document.querySelector('#syncTime');
 if(!reportImport&&reportLoadState!=='ready'){
  const loading=reportLoadState==='loading';footer.textContent=loading?'Consultando planilha…':'Não foi possível atualizar a planilha';
  view.innerHTML=reportSourceControls()+`<div class="empty-state" role="status"><h2>${loading?'Carregando registros reais…':'Dados de ponto indisponíveis'}</h2><p>${loading?'Aguarde a leitura da planilha conectada.':'A conexão com a planilha falhou. Nenhum dado de reserva foi usado neste relatório.'}</p>${loading?'':'<button class="filter" onclick="reportLoadState=\'loading\';renderTimeReport();refreshData()">Tentar novamente</button>'}</div>`;return;
 }
 const source=reportImport||data;const rows=reportNormalized(source),filters={...f,from:f.mode==='today'?f.day:f.from,to:f.mode==='today'?f.day:f.to};
 const result=core.summarize(rows,filters),unique=(key,label=key)=>[...new Map(rows.filter(r=>r[key]).map(r=>[r[key],r[label]])).entries()].sort((a,b)=>a[1].localeCompare(b[1],'pt-BR'));
 const select=(label,key,options)=>`<label>${label}<select onchange="reportSet('${key}',this.value)">${reportOptions(options,f[key])}</select></label>`;
 const dateInput=(label,key)=>`<label>${label}<input type="date" value="${esc(f[key])}" onchange="reportSet('${key}',this.value)"></label>`;
 const warningCount=rows.filter(r=>!r.date).length;
 const segmentRow=r=>`<tr><td>${esc(r.worker)}<small>${reportDate(r.date)}</small></td><td>${esc(r.entry)||'—'}</td><td>${esc(r.exit)||'—'}${r.exitDate&&r.exitDate!==r.date?`<small>${reportDate(r.exitDate)}</small>`:''}</td><td class="report-number">${core.duration(r.minutes)}<small>${esc(r.basis)}</small></td><td>${esc(r.project)}${r.client?`<small>${esc(r.client)}</small>`:''}</td><td><span class="report-status">${esc(r.status)}</span>${r.sourceStatus?`<small>Origem: ${esc(r.sourceStatus)}</small>`:''}</td><td>${r.issues.map(esc).join('<br>')}${r.correction?`<p>Correção: ${esc(r.correction)}</p>`:''}${r.notes?`<p>${esc(r.notes)}</p>`:''}${!r.issues.length&&!r.correction&&!r.notes?'—':''}</td></tr>`;
 const segmentsTable=rs=>reportTable(['Funcionário / data','Entrada','Saída','Total','Cliente / projeto','Status','Divergências / correções'],rs.map(segmentRow).join(''));
 let body='';
 if(result.selected.length){
  if(f.mode==='today'){
   const ordered=[...result.selected].sort((a,b)=>(f.sort==='asc'?1:-1)*((a.minutes??-1)-(b.minutes??-1)));
   body=`<div class="report-heading"><h2 class="section-title">${f.day===reportToday()?'Hoje':reportDate(f.day)}</h2><label class="report-check"><input type="checkbox" ${f.consolidate?'checked':''} onchange="reportSet('consolidate',this.checked)"> Consolidar por funcionário</label></div>`;
   body+=f.consolidate?result.daily.map(g=>`<details class="report-group"><summary><strong>${esc(g.label)}</strong><span>${reportGroupHours(g)} · ${g.segments.length} segmento(s)</span></summary>${segmentsTable(g.segments)}</details>`).join(''):segmentsTable(ordered);
  }else{
   body=`<h2 class="section-title">Horas por funcionário</h2>${reportTable(['Funcionário','Horas acumuladas','Segmentos'],result.workers.map(g=>`<tr><td>${esc(g.label)}</td><td>${reportGroupHours(g)}</td><td>${g.segments.length}</td></tr>`).join(''))}<h2 class="section-title report-space">Distribuição por cliente / projeto</h2>${reportTable(['Projeto','Horas','% das horas filtradas','Custo calculável (USD)'],result.projects.map(g=>`<tr><td>${esc(g.label)}</td><td>${reportGroupHours(g)}</td><td>${g.percent===null?'—':g.percent.toLocaleString('pt-BR',{maximumFractionDigits:2})+'%'}<div class="report-bar" aria-hidden="true"><span style="width:${g.percent??0}%"></span></div></td><td>${g.unknownCost?'A confirmar'+(g.cost?' · parcial '+usd(g.cost):''):usd(g.cost)}</td></tr>`).join(''))}<details class="report-group report-space"><summary>Ver segmentos, status e correções</summary>${segmentsTable([...result.selected].sort((a,b)=>(f.sort==='asc'?1:-1)*((a.minutes??-1)-(b.minutes??-1))))}</details>`;
  }
 }else body='<div class="empty-state">Nenhum registro encontrado para os filtros selecionados.</div>';
 view.innerHTML=reportSourceControls()+`<div class="report-tabs" role="group" aria-label="Visão do relatório"><button class="filter ${f.mode==='today'?'active':''}" aria-pressed="${f.mode==='today'}" onclick="reportSet('mode','today')">Hoje</button><button class="filter ${f.mode==='general'?'active':''}" aria-pressed="${f.mode==='general'}" onclick="reportSet('mode','general')">Geral / Acumulado</button></div><div class="report-filters">${f.mode==='today'?dateInput('Data','day'):dateInput('De','from')+dateInput('Até','to')}${select('Funcionário','worker',unique('workerKey','worker'))}${select('Cliente','client',unique('client'))}${select('Projeto','project',unique('projectId','project'))}${select('Status','status',unique('status'))}<label>Ordenar por total<select onchange="reportSet('sort',this.value)"><option value="desc" ${f.sort==='desc'?'selected':''}>Maior → menor</option><option value="asc" ${f.sort==='asc'?'selected':''}>Menor → maior</option></select></label><button class="filter" onclick="reportReset()">Limpar filtros</button></div>${result.invalidPeriod?'<p class="report-warning" role="alert">Informe as duas datas, com início anterior ou igual ao fim.</p>':''}${warningCount?`<p class="report-warning">${warningCount} registro(s) com data inválida, fora dos totais por período. Corrija a data na planilha.</p>`:''}<div class="report-kpis" aria-live="polite"><div><span>Total de funcionários</span><strong>${result.count}</strong></div><div><span>Total de horas${result.excluded?' (parcial)':''}</span><strong>${core.duration(result.total)}</strong></div><div><span>Média por funcionário${result.excluded?' (parcial)':''}</span><strong>${core.duration(result.average)}</strong></div></div><p class="note report-method">Fonte: ${reportImport?esc(reportImport.label):'aba Labor da planilha conectada'}. Cada linha é um segmento de projeto. Totais e percentuais consideram os filtros atuais; a média divide as horas pelo número de funcionários exibidos. Horários completos prevalecem sobre horas lançadas. ${result.excluded?`<strong>${result.excluded} segmento(s) sem duração confirmada excluído(s) das horas e custos.</strong>`:''}</p>${body}<p class="note report-method">Custos usam a duração de cada segmento × taxa/hora informada. Taxa ausente ou zero fica a confirmar. Horas sem entrada/saída são identificadas como “Horas lançadas”. Correções são lidas da planilha; este relatório não altera os lançamentos.</p>`;
 if(reportImport)footer.textContent='Consulta guardada neste navegador · sem gravação na planilha';else updateSyncTime();
}
